var requireDirectory = require('require-directory');
var directory =__dirname;
console.log(directory);
//var api = requireDirectory('./api/index.js');
//console.log(api);
//var api =apiPath.normalize("..//api");
//var api = require('./api');
//api.save.chkfn();
//api.Deletejsfile.Delete();
//console.log("idheebjebrf");